name: pyrsig-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - pandas
  - pip:
    - sphinx
    - sphinx_gallery
    - sphinx-copybutton
    - pydata-sphinx-theme<0.9.0
    - myst_nb
    - sphinx_design
